### PR TITLE
Skip blockage

### PR DESCRIPTION
**Pull request by Avielyo10**
Skip blocking if one or more resources is not operational.

### CODE REVIEW

**Comment by ggallen** [comment]
I must be missing something here.  If something is not operational, why would we skip blocking?  The whole point of this plugin is to block in this case, isn't it?

**Comment by Avielyo10** [comment]
@ggallen, Alex needs this skip for his smoke tests, I think it's because he don't want this to block the whole pipeline only to wait for a certain amount of time for some specific resources.

**Q:**
Blockage will return a metrics but if some resource has been blocked for some reason, let say "Major Outage", then moved to "Performance Issues" and then after a while it moved to "Operational". The data in the metrics will show you the status of "Major Outage", even though now it's "Operational" and in between it was "Performance Issues". is this intended?

**Comment by scoheb** [comment]
@Avielyo10 so the skipping option is only for testing?

To answer your question, the only thing we wanted to have is the fact it was blocked and for how long. The status type of the blocking was not as important.

@ggallen thoughts?

**Comment by Avielyo10** [comment]
@scoheb, Yes Alex wants to write smoke test integration with Semaphore, so he asked me to add this skipping option.
Also for this purpose I added a time limit to the cachetWaitForResources step.

**Comment by abraverm** [comment]
Blocking is greate for software testing, but for generic automation skipping a step can be useful when the automation run is important by itself, specifically in monitoring and health checks. The idea is that no mattter what the build will be executed, even if some\all steps were skipped because of some reason. I will get notification that the build skipped some steps because of resource availability, and that is a valid state of build for me.

**Comment by scoheb** [comment]
It seems that you are not basing yourself on #8 . It makes reviewing this PR more difficult. Can you combine this and #8 together? And also squash your commits?

**Comment by ggallen** [comment]
I agree with @scoheb , please put all these changes in one PR and squash all the commits.

I think the timeout is useful, but it needs to be configurable in both the pipeline and the UI.  It should also be specified in seconds. The default timeout should be 0 (not Integer.MAX_INTEGER), which will mean wait forever (i.e. no timeout).

If a timeout is reached, then the option to either abort or skip comes into play. This should default to abort and should also be configurable both in pipeline and the UI.

**Pull request closed without merging**
