### PR TITLE
Adding CachetGatingWaitForResourcesStep.java

### PR DESCRIPTION
**Pull request by Avielyo10**
Also adding the option to skip the blockage

### CODE REVIEW

**Comment by Avielyo10** [comment]
@ggallen I thought you meant to add the timeout and the option to ignore the failure to the step itself.
IMHO `waitForResourcesStep` needs to do waiting, therefore timout is needed there.

If you guys want it that way that's fine, but the return value from this `waitForResourcesStep` will always be a map of the required resources with the value 0, since the waiting has already occurred on the job property configuration because of the blockage.

If you want to move those options to the job property configuration then `waitForResourcesStep` is useless, the gating matrix already has that information.

**Comment by abraverm** [comment]
My 2 cents: I prefer per step configuration, as job process owner I decide when to use this functionality and I prefer to have agility to decide how much timeout or should be a failure per step. From job maintenance, it would be nice to have "global" settings for job but it shouldn't be one or the other.

**Comment by olivergondza** [comment]
I confess I am getting a bit lost in use-cases and the way users are expected to implement them using this plugin. Some random thoughts at least:

- Adding timeout to wait for resources to be healthy makes sense to me.
- Configuring the step to wait for resources to be healthy and continue with build execution if they are not healthy makes less sense to me.

**Comment by Avielyo10** [comment]
Irrelevant. Closing.

**Pull request closed without merging**
